### ISSUE TITLE
training script

### ISSUE THREAD

**Issue by Sunnyiren** [ViTAE-Transformer/ViTAE-Transformer-Matting#4]
Hi! Thanks for your amazing work! I learned a lot from it. And I have noticed that the full scripts for training haven't been released. Is there a plan for that? Thanks a lot!

**Comment by xymsh** [comment]
Thank you for your watching. 

Since our paper is still in submission, we will release the training scripts and the checkpoints later. You can star and watch our repo to get noticed once these resources are available. You can also follow our previous work P3M ([Github repo](https://github.com/JizhiziLi/P3M)) for reference. Thank you!
